### ISSUE TITLE
自动管理证书，无法访问。如果要手动导入根CA证书那是在哪里呢？

### ISSUE THREAD

**Issue by byphp-com** [xpf0000/FlyEnv#132]
RT

**Comment by byphp-com** [comment]
查看配置查到了，写一下吧，让我们知道应该在那里去找，配置

**Comment by byphp-com** [comment]
并且，不只是在Linux中要手动导入根CA证书，Macos上也需要

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
