### ISSUE TITLE
我就安装一个php5.6，怎么把其他软件都升级更新了一遍?

### ISSUE THREAD

**Issue by Lxj96** [xpf0000/FlyEnv#140]
我只是点击安装了php@5.6版本,没想到Brew把整个系统的软件升级了一遍,比如mysql从8.0.39升级到了8.0.42
<img width="934" alt="image" src="https://github.com/user-attachments/assets/8403b537-772f-4516-ad12-36d39f82586b">
<img width="841" alt="image" src="https://github.com/user-attachments/assets/9e1b9c91-d6e5-46fe-8a72-ec14713c4c3c">

**Comment by xpf0000** [comment]
1. 这是brew自身特性。 brew安装的各个软件是通用一套基础库的。例如icu4c。 你现在装了个PHP7.4. 是在目前的icu4c版本的基础上构建的。 比如icu4c70.  过了几个月， 你再装个PHP8.2.   这时候依赖项icu4c已经升级到icu4c74了。 PHP8.2是在icu4c74的基础上构建的。 所以brew安装PHP8.2时， 会自动升级依赖项icu4c到icu4c74。 这样一来， 原来装的PHP7.4肯定无法用了， 所以同样需要升级。
2. 你可以使用命令行自行管理各个服务的版本。 软件会自动识别
