### ISSUE TITLE
java项目添加后，无法获取。需要把软件重启后才能看见。

### ISSUE THREAD

**Issue by maoyusan** [xpf0000/FlyEnv#141]
如题，
![Uploading 957b684f-0a21-4711-a3d7-ced40f8f60e9.png…]()

**Comment by maoyusan** [comment]
![Uploading 957b684f-0a21-4711-a3d7-ced40f8f60e9.png…]()

**Comment by maoyusan** [comment]
编辑项目例如修改端口，配置依然没有刷新，也需要重新软件才能看到

**Comment by xpf0000** [comment]
已处理， 重新下载安装
