### ISSUE TITLE
无法设置环境变量

### ISSUE THREAD

**Issue by JuanFaC** [xpf0000/FlyEnv#143]
MacOs版本 15.1
phpWebStudy版本4.5.1
已正确输入电脑密码，使用homebrew安装的phpWebStudy
1. 设置php环境变量，redis环境变量，mysql环境变量，java环境变量一直转圈，无法一键快捷设置环境变量
2. NodeJs版本管理工具安装nvm，使用homebrew方式安装，查看.zprofile中，发现export NVM_DIR="/Users/orange/.nvm"，不是nvm实际安装路径

**Comment by xpf0000** [comment]
1. 升级最新版再试下
2. NVM_DIR默认就是~/.nvm  这个是统一的, 不管用哪种方式安装的 NVM

**Comment by JuanFaC** [comment]
更新到4.5.5已解决无法设置环境变量的问题
创建软连接后nvm可正常使用
