### ISSUE TITLE
Add to PATH doesn't work

### ISSUE THREAD

**Issue by RobiNN1** [xpf0000/FlyEnv#146]
It seems add to PATH doesn't work, tested in php and apache. It loads and nothing happens, it can't find `php -v` in the terminal.

Clean macos 15.1

<img width="384" alt="Snímka obrazovky 2024-11-16 o 12 49 41" src="https://github.com/user-attachments/assets/86e18040-931b-4e3f-8f50-1772554eb7c8">

I switched to mac and overall the app is a great alternative to laragon (win only).

**Comment by xpf0000** [comment]
what version of phpwebstudy? the lasted version is 4.5.5. if not, you can reinstall 4.5.5, and retry.

**Comment by RobiNN1** [comment]
Latest version, it was autoupdated

**Comment by xpf0000** [comment]
ok. i will build a test version. add some debug output.  can you help me test it?

**Comment by RobiNN1** [comment]
yes, of course

**Comment by xpf0000** [comment]
[FlyEnv-4.5.5-arm64-debug.dmg](https://github.com/xpf0000/FlyEnv/releases/download/v4.5.5/FlyEnv-4.5.5-arm64-debug.dmg)
try this. and then post ~/Library/PhpWebStudy/server/debug.log

**Comment by RobiNN1** [comment]
I don't see debug.log file in that folder

**Comment by xpf0000** [comment]
click Add to PATH first.

**Comment by xpf0000** [comment]
1. see /System/Applications.  check if PhpWebStudy.app exists. if exists. remove it. 
2. remove FlyEnv.app
3. install the debug version
4. click Add to PATH
5. check if debug.log exists. if exists. post it

**Comment by xpf0000** [comment]
I think I found the cause of the problem. I will post an update later

**Comment by xpf0000** [comment]
The problem has been solved. Re-download and install and try again.

**Comment by RobiNN1** [comment]
thanks, it works now
