### ISSUE TITLE
MySQL连接时间有点久

### ISSUE THREAD

**Issue by 1532332928** [xpf0000/FlyEnv#148]
目前正在使用MySQL8.0的版本，不管是在PHP还是使用Navicat Premium Lite 17工具连接时间都需要2s以上，在开发过程有点影响

**Comment by xpf0000** [comment]
localhost 换成 127.0.0.1 试试

**Comment by 1532332928** [comment]
> localhost 换成 127.0.0.1 试试
的确，换127.0.0.1快了，这是什么原理呢

**Comment by xpf0000** [comment]
localhost 应该是多了个解析成 IP 的步骤.
