### ISSUE TITLE
brew  获取不到列表无法下载

### ISSUE THREAD

**Issue by dadLJH** [xpf0000/FlyEnv#162]
brew   php、mysql、nginx等等获取不到无法下载   ，切换源也不行

**Comment by xpf0000** [comment]
1. 如果全部都获取不到, 就是你安装 brew 时候 没有安装 brew core.  重新安装 brew 就行了 
可以使用如下命令看下
```
brew -v
```
看下有没有 Homebrew/homebrew-core 

2. 如果确认已正确安装brrew, 那就是网络问题, 建议使用代理. 或者自行在命令行安装相关服务. 安装完FlyEnv 会自动检测到

**Comment by Yuuuu9658** [comment]
退回到4.5.6版本就行了，后期版本要许可证才能创建3个以上站点，还把网站配置文件加密了，防止你退回，但是反而把最基本的软件安装做坏了，有点无语
